### ISSUE TITLE
Notifications Protocol Conformance Classes

### ISSUE THREAD

**Issue by csarven** [solid/notifications#106]
Add a Conformance Classes section listing the roles eg. Notification Server, Client, that the Solid Notifications Protocol specifies. The criteria for each of the roles can be described throughout the specification.

**Comment by elf-pavlik** [comment]
I proposed some new terminology in #108 

We already have #49 and I recall a discussion that we should minimize assumptions on how Subscriber and Publisher internally choose to couple or separate different responsibilities.


I'd look separately at the Subscription Flow and Notifications Flow. The first seems a bit simpler since the client/server roles match the subscriber/publisher. I think we have distinct:

* Subscriber - client sending subscription request
* Topic publisher - server publishing the topic
  * Storage description
  * Subscription channel 

I think we shouldn't be careful how we look at the publisher side in the subscription flow, probably we can consider it as a single entity even though internally the implementations may choose to separate topics publisher from subscription channels.

Now for the Notifications flow, depending on the source (pick-up) or target (delivery) flow the client/server roles will work in opposite way:

* source (pick-up)
  * subscriber - client
  * publisher - server
* target (delivery)
  * subscriber - server
  * publisher - client

We probably also externally want to just look at Subscriber and Publisher leaving out all the coupling or separation related to notifications source and notifications target as their implementation details.
