### ISSUE TITLE
Replace 'endpoint' with API

### ISSUE THREAD

**Issue by acoburn** [solid/notifications#30]
For an ecosystem that is based on capability/feature discovery, it is arguably better to think less about "endpoints" and more about "hypermedia APIs". As such, I would propose removing instances of 'endpoint' in this specification and replacing them with either 'API' or 'URI', as appropriate.

**Comment by TallTed** [comment]
"Endpoint" and "API" are not interchangeable terms.  Neither are "API" and "URI", nor "endpoint" and "URI".

"Endpoint" is well understood as the "agent to which an API call (including an HTTP method call, for which a resource URI is typically an input) is issued".

An "API" provides function signatures, including inputs and outputs.  These might be passed within a URI (typically as part of the query segment) for a simple HTTP `GET`, or in the payload of an HTTP `POST`.

There is nothing that says that a Solid server cannot respond to an incomplete (including empty) API call with the signature of that API, on which the original caller may act by including any missing inputs in a subsequent call.

[OpenAPI 3.0 (née Swagger)](https://swagger.io/specification/) seems well suited to the requirements here, and I'm rather surprised that it's not being put to use.

**Comment by elf-pavlik** [comment]
I don't think we should rely on nuances of endpoint vs API. Personally, I think we should make a distinction between

* subscription URL - which always requires AuthN and returns subscription details
* notification URL - in most cases a capability URL tied to AuthN from subscription
  * notification source - current subscription type call it 'endpoint' - a subscriber can establish a connection with the publisher to receive notifications
  * notification target - currently only WebHooks subtype defines it, it doesn't use source since notifications are being sent by publisher establishing a connection with subscriber

**Comment by elf-pavlik** [comment]
To clarify
* **source** would be used instead of *endpoint* in:
  * WebSockets Subscription type - `wss:`
  * EventSource Subscription type - `https:`
  * StreamingHTTP Subscription type - `https:`
 * **target** would be used in:
   * WebHook Subscription type 

Once @csarven proposes LDN Subscription type we would see which one applies there, I would guess it would provide some inbox as *target* so probably I also wouldn't use *source*. Just guessing here without seeing the actual LDN sub type proposal.

**Comment by elf-pavlik** [comment]
#43 is addressing this issue
