### ISSUE TITLE
Interchangeable use of notification channel type and subscription type

### ISSUE THREAD

**Issue by csarven** [solid/notifications#71]
In the Notifications Protocol, the description of a notification channel includes its type, feature, and subscription. The value of the type is expressed as the same value as the subscription type. The question is whether the subscription type, e.g., `WebSocketSubscription2021` is misleading or misused here as part of the notification channel type.

**Comment by uvdsl** [comment]
I would like both, seems most clear to me...

Example: Representation of a Notification Subscription Metadata Resource. 
```turtle
Content-Type: text/turtle

@prefix notify: <http://www.w3.org/ns/solid/notifications#> .

<> notify:subscriptionChannel <#channel-0> .

<#channel-0>
  a  notify:SubscriptionChannel ;
  notify:subscriptionType notify:WebSocketSubscription2021;
  notify:subscription <https://websocket.example/subscription> ;
  notify:feature notify:state, notify:rate, notify:expiration .
```

In terms of naming... I think `subscriptionChannel` would by more consistent with the other terms... but ultimately... I do not mind actually.

However, I would propose to use `service` instead of `channel` because for `channel` I immediately think about the channel via which notifications will be delivered. The subscription and the resulting notifications may not come over the same "channel", not even same protocols...

So maybe something like

```turtle
Content-Type: text/turtle

@prefix notify: <http://www.w3.org/ns/solid/notifications#> .

<> notify:subscriptionService <#service-0> .

<#service-0>
  a  notify:SubscriptionService ;
  notify:subscriptionType notify:WebSocketSubscription2021;
  notify:subscription <https://websocket.example/subscription> ;
  notify:feature notify:state, notify:rate, notify:expiration .
```

**Comment by csarven** [comment]
I'm in favour of the notion of a "notification service" (e.g., using `notify:Service` in RDF), and replacing the notion of "notification channel".

"notification service" is a generalisation. Notification services can be specialised, e.g., with a subscription capability. From that perspective, we just need to clarify the relationship where a `notify:WebSocketSubscription2021` is a  subClassOf `notify:Service`. Then there may not be a need for `notify:subscriptionType`.
